# Generated by Django 5.0.2 on 2024-03-11 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machine', '0001_initial'),
        ('part', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='parts',
            field=models.ManyToManyField(blank=True, related_name='related_machines', through='part.PartMachineRelation', to='part.part'),
        ),
        migrations.AddField(
            model_name='machineuserrelation',
            name='machine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='machine.machine'),
        ),
        migrations.AddField(
            model_name='machineuserrelation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='machine',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='machines', through='machine.MachineUserRelation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='machineuserrelation',
            unique_together={('machine', 'user')},
        ),
    ]
