# Generated by Django 5.0.2 on 2024-03-07 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machine', '0001_initial'),
        ('part', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='parts',
            field=models.ManyToManyField(blank=True, related_name='related_machines', through='part.PartMachineRelation', to='part.part'),
        ),
        migrations.AddField(
            model_name='machineuserrelation',
            name='machine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='machine.machine'),
        ),
    ]
