# Generated by Django 5.0.2 on 2024-03-17 12:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0003_machine_pdf_machine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='characteristics',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, null=True, size=None),
        ),
    ]
