# Generated by Django 5.0.2 on 2024-03-03 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='part_images/')),
                ('cad_file', models.FileField(blank=True, null=True, upload_to='part_cad/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='part_pdf/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartMachineRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.machine')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='part.part')),
            ],
            options={
                'unique_together': {('part', 'machine')},
            },
        ),
        migrations.AddField(
            model_name='part',
            name='machines',
            field=models.ManyToManyField(related_name='related_parts', through='part.PartMachineRelation', to='machine.machine'),
        ),
    ]
