# Generated by Django 5.0.2 on 2024-03-11 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machine', '0002_initial'),
        ('part', '0001_initial'),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='providers',
            field=models.ManyToManyField(related_name='supplied_parts', to='providers.providers'),
        ),
        migrations.AddField(
            model_name='partmachinerelation',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.machine'),
        ),
        migrations.AddField(
            model_name='partmachinerelation',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='part.part'),
        ),
        migrations.AddField(
            model_name='part',
            name='machines',
            field=models.ManyToManyField(related_name='related_parts', through='part.PartMachineRelation', to='machine.machine'),
        ),
        migrations.AlterUniqueTogether(
            name='partmachinerelation',
            unique_together={('part', 'machine')},
        ),
    ]
